create table cars (
                      id integer generated by default as identity,
                      brand varchar(20) not null,
                      model varchar(50) not null,
                      volume double precision not null,
                      year integer not null,
                      color varchar(30) not null,
                      category varchar(30) not null
);